/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


#include<stdio.h>
main()
{
	int i=1,j=2,count=0,sum,total=0,final=0;
	do
	{
		sum=i+j;
		i=j;
		j=sum;
		if(j>4000000)
		{
			break;
		}
		else
		{ 
			if(j%2==0)
			{
				total=total+j;
		}
		}
			
	}while(i>0);
		final=total+2;// 2 should be added to the sum,as this is not involved in the sum
		printf("%d",final);
	
	getch();
	
}
